### ISSUE TITLE
Talend 8 - tJasperReportExec in combination with tFileExcel - Exception in thread "main"

### ISSUE THREAD

**Issue by Jens2205** [jlolling/talendcomp_tJasperReportExec#11]
Hi Jan,

we found a library conflict between tJasperReportExec and tFileExcel*.
If we using both components in a Talend-Job (Studio 8 und Java 11), we got the following error:
`Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.xmlbeans.XmlOptions.put(java.lang.Object)'
	at org.apache.poi.xssf.model.SharedStringsTable.<clinit>(SharedStringsTable.java:94)
	at org.apache.poi.ooxml.POIXMLFactory.newDocumentPart(POIXMLFactory.java:94)
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:615)
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:525)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:474)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:265)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:259)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
	at de.jlo.talendcomp.excel.SpreadsheetFile.initializeWorkbook(SpreadsheetFile.java:476)
	at vts_and_dwh.excel_vs_jasper_0_1.Excel_vs_Jasper.tFileExcelWorkbookOpen_1Process(Excel_vs_Jasper.java:797)
	at vts_and_dwh.excel_vs_jasper_0_1.Excel_vs_Jasper.tJava_1Process(Excel_vs_Jasper.java:500)
	at vts_and_dwh.excel_vs_jasper_0_1.Excel_vs_Jasper.runJobInTOS(Excel_vs_Jasper.java:1097)
	at vts_and_dwh.excel_vs_jasper_0_1.Excel_vs_Jasper.main(Excel_vs_Jasper.java:935)` 

Or in an other Job-scenario:
`Exception in thread "main" java.lang.NoSuchMethodError: 'byte[] org.apache.commons.io.IOUtils.byteArray(int)'
	at org.apache.commons.io.output.AbstractByteArrayOutputStream.needNewBuffer(AbstractByteArrayOutputStream.java:104)
	at org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.<init>(UnsynchronizedByteArrayOutputStream.java:51)
	at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:139)
	at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:209)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:143)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:175)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
	at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:47)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
	at de.jlo.talendcomp.excel.SpreadsheetFile.initializeWorkbook(SpreadsheetFile.java:455)` 

To reproduce this error we setup a very simple Job shown in the following screenshots:  
![image](https://github.com/jlolling/talendcomp_tJasperReportExec/assets/29700391/e1b00b5f-5f69-4a25-adc0-1662025054c0)

And if we comment out the tJasperReportExec everything is fine:
![image](https://github.com/jlolling/talendcomp_tJasperReportExec/assets/29700391/a07cd4c2-c1b7-4905-a990-7de18495209b)

Thanks for your help!
Best regards
Susanne & Jens

**Comment by jlolling** [comment]
Damn,

Obviously I need central properties for the most used libraries to take care the versions are always the same.
Yes both components use partly the same artefacts but different versions.

I will update the tJasperReportExec to solve this conflict.

Best regards
Jan

**Comment by Jens2205** [comment]
Hi Jan,

could you give us an update on this issue?

Thanks in advance!
Best regards
Susanne & Jens

**Comment by jlolling** [comment]
I am on the way to solve this. I convinced I will solve it this week.

**Comment by jlolling** [comment]
The problem I am facing is, I had to patch the Apache POI library to solve an issue there and now I have to take care the patch can also be used for the JasperLibrary.

**Comment by jlolling** [comment]
Try the new release please: https://github.com/jlolling/talendcomp_tJasperReportExec/releases/tag/7.3

**Comment by jlolling** [comment]
I have used the same manually patched lib as for the Excel components because the patch for the original Apache POI project is much more difficult and needs more time, you do not have I guess.

**Comment by jlolling** [comment]
I have used the same manually patched lib as for the Excel components because the patch for the original Apache POI project is much more difficult and needs more time, you do not have I guess.

**Comment by jlolling** [comment]
I have used the same manually patched lib as for the Excel components because the patch for the original Apache POI project is much more difficult and needs more time, you do not have I guess.

**Comment by Jens2205** [comment]
Thank's again, for your support!

Best regards
Susanne & Jens
