### ISSUE TITLE
Subreport on database

### ISSUE THREAD

**Issue by briceledru** [jlolling/talendcomp_tJasperReportExec#5]
Hello,

I have created a report with subreport but when I execute this component in Talend. i have the following message : 
Exception in component tJasperReportExec_5 (Talend_Job)
java.lang.NullPointerException
	at de.jlo.talendcomp.jasperreportexec.JasperReportExecuter.compileReport(JasperReportExecuter.java:437)
	at de.jlo.talendcomp.jasperreportexec.JasperReportExecuter.access$000(JasperReportExecuter.java:120)
	at de.jlo.talendcomp.jasperreportexec.JasperReportExecuter$1.visitSubreport(JasperReportExecuter.java:461)
	at net.sf.jasperreports.engine.util.JRDelegationVisitor.visitSubreport(JRDelegationVisitor.java:136)
	at net.sf.jasperreports.engine.base.JRBaseSubreport.visit(JRBaseSubreport.java:171)
	at net.sf.jasperreports.engine.util.ElementsVisitorUtils.visitElements(ElementsVisitorUtils.java:65)
	at net.sf.jasperreports.engine.base.JRBaseElementGroup.visit(JRBaseElementGroup.java:200)
	at net.sf.jasperreports.engine.util.JRElementsVisitor.visitBand(JRElementsVisitor.java:124)
	at net.sf.jasperreports.engine.util.JRElementsVisitor.visitSection(JRElementsVisitor.java:114)
	at net.sf.jasperreports.engine.util.JRElementsVisitor.visitReport(JRElementsVisitor.java:86)
	at net.sf.jasperreports.engine.util.JRElementsVisitor.visitReport(JRElementsVisitor.java:56)
	at de.jlo.talendcomp.jasperreportexec.JasperReportExecuter.compileReport(JasperReportExecuter.java:440)
	at de.jlo.talendcomp.jasperreportexec.JasperReportExecuter.compileReport(JasperReportExecuter.java:357)
...

I have passed the parameter "SUBREPORT_DIR" and for the connection, I use the variable of the master report

The subreports are in the same directory as the principal report

I use Talend 7.2 and iReport 5.6.

Thank you in advance

**Comment by jlolling** [comment]
Could you please update your post with the message you got.

**Comment by briceledru** [comment]
Hello,

do you have an answer ?

**Comment by jlolling** [comment]
I cannot reproduce it. Could you please send me your report design (jrxml) at jan.lolling@gmail.com ?

**Comment by jlolling** [comment]
I have checked the code and this issue is solved. It happens if a section has no type (which happens if you have a JasperBook) and then a NullPointerException was thrown. This is solved since version 7.0 of the component.
